-- Create "archives" table
CREATE TABLE `archives` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `name` text NOT NULL, `created_at` datetime NOT NULL, `duration` datetime NOT NULL, `borg_id` text NOT NULL, `archive_repository` integer NOT NULL, CONSTRAINT `archives_repositories_repository` FOREIGN KEY (`archive_repository`) REFERENCES `repositories` (`id`) ON DELETE NO ACTION);
-- Create "backup_profiles" table
CREATE TABLE `backup_profiles` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `name` text NOT NULL, `prefix` text NOT NULL, `directories` json NOT NULL, `is_setup_complete` bool NOT NULL DEFAULT (false), `backup_profile_backup_schedule` integer NULL, CONSTRAINT `backup_profiles_backup_schedules_backup_schedule` FOREIGN KEY (`backup_profile_backup_schedule`) REFERENCES `backup_schedules` (`id`) ON DELETE SET NULL);
-- Create "backup_schedules" table
CREATE TABLE `backup_schedules` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `hourly` bool NOT NULL DEFAULT (false), `daily_at` datetime NULL, `weekly_day` text NULL, `weekly_at` datetime NULL, `monthly_day` integer NULL, `monthly_at` datetime NULL, `backup_schedule_backup_profile` integer NOT NULL, CONSTRAINT `backup_schedules_backup_profiles_backup_profile` FOREIGN KEY (`backup_schedule_backup_profile`) REFERENCES `backup_profiles` (`id`) ON DELETE NO ACTION);
-- Create "repositories" table
CREATE TABLE `repositories` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `name` text NOT NULL, `url` text NOT NULL, `password` text NOT NULL);
-- Create "backup_profile_repositories" table
CREATE TABLE `backup_profile_repositories` (`backup_profile_id` integer NOT NULL, `repository_id` integer NOT NULL, PRIMARY KEY (`backup_profile_id`, `repository_id`), CONSTRAINT `backup_profile_repositories_backup_profile_id` FOREIGN KEY (`backup_profile_id`) REFERENCES `backup_profiles` (`id`) ON DELETE CASCADE, CONSTRAINT `backup_profile_repositories_repository_id` FOREIGN KEY (`repository_id`) REFERENCES `repositories` (`id`) ON DELETE CASCADE);
