reviews:
  high_level_summary: false
  poem: false
  path_filters:
    - '**'
    - '!backend/ent/*'
    - '!backend/ent/archive/**'
    - '!backend/ent/authsession/**'
    - '!backend/ent/backupprofile/**'
    - '!backend/ent/backupschedule/**'
    - '!backend/ent/cloudrepository/**'
    - '!backend/ent/hook/**'
    - '!backend/ent/notification/**'
    - '!backend/ent/predicate/**'
    - '!backend/ent/pruningrule/**'
    - '!backend/ent/repository/**'
    - '!backend/ent/runtime/**'
    - '!backend/ent/settings/**'
    - '!backend/ent/user/**'
