version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml
  db: ./Taskfile.db.yml
  dev: ./Taskfile.dev.yml
  proto: ./proto/Taskfile.proto.yml

vars:
  APP_NAME: "arco"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'
  VERSION:
    sh: sed -n 's/.*"\."\s*:\s*"\([0-9.]*\)".*/\1/p' .release-please-manifest.json

tasks:
  build:
    desc: Builds the application
    cmds:
      - task: '{{if eq .PLATFORM "darwin/universal"}}darwin:build:universal{{else}}{{OS}}:build{{end}}'

  package:
    desc: Packages a production build of the application
    cmds:
      - task: '{{if eq .PLATFORM "darwin/universal"}}darwin:package:universal{{else}}{{OS}}:package{{end}}'

  run:
    desc: Runs the application
    cmds:
      - task: "{{OS}}:run"

  test:
    desc: Run tests
    silent: true
    deps:
      - task: dev:gen:mocks
    preconditions:
      - mkdir -p frontend/dist
      - touch frontend/dist/index.html
    cmds:
      - |
        go test -cover -mod=readonly --timeout 5m $(go list ./... | grep -v ent) -json | \
        tee >(./scripts/test-output-processor.sh) | \
        ./scripts/test-summary.sh

  test:raw:
    desc: Run tests with raw output
    deps:
      - task: dev:gen:mocks
    preconditions:
      - mkdir -p frontend/dist
      - touch frontend/dist/index.html
    cmds:
      - go test -v -cover -mod=readonly --timeout 5m $(go list ./... | grep -v ent)

  test:detailed:
    desc: Run tests with detailed output
    silent: true
    deps:
      - task: dev:gen:mocks
    preconditions:
      - mkdir -p frontend/dist
      - touch frontend/dist/index.html
    cmds:
      - |
        go test -cover -mod=readonly --timeout 5m $(go list ./... | grep -v ent) -json | \
        tee >(jq --unbuffered -r '
          if .Action == "run" and .Test == null then
            "🔄 Starting: " + .Package
          elif .Action == "pass" and .Test == null then
            "✅ " + .Package + " (" + (.Elapsed // 0 | . * 100 | round / 100 | tostring) + "s)"
          elif .Action == "fail" and .Test == null then
            "❌ " + .Package + " - FAILED (" + (.Elapsed // 0 | . * 100 | round / 100 | tostring) + "s)"
          elif .Action == "pass" and .Test != null then
            "  ✅ " + .Test + " (" + (.Elapsed // 0 | . * 100 | round / 100 | tostring) + "s)"
          elif .Action == "fail" and .Test != null then
            "  ❌ " + .Test + " (" + (.Elapsed // 0 | . * 100 | round / 100 | tostring) + "s)"
          elif .Action == "output" and (.Output // "" | type == "string") and (.Output | test("^coverage: [0-9.]+% of statements$")) then
            "  📊 " + (.Output | gsub("\\t|\\n"; "") | gsub("^\\s+|\\s+$"; ""))
          else
            empty
          end
        ') | \
        ./scripts/test-summary.sh
