version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml
  db: ./Taskfile.db.yml
  dev: ./Taskfile.dev.yml
  proto: ./proto/Taskfile.proto.yml

vars:
  APP_NAME: "arco"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'
  VERSION:
    sh: sed -n 's/.*"\."\s*:\s*"\([0-9.]*\)".*/\1/p' .release-please-manifest.json

tasks:
  build:
    desc: Builds the application
    cmds:
      - task: '{{if eq .PLATFORM "darwin/universal"}}darwin:build:universal{{else}}{{OS}}:build{{end}}'

  package:
    desc: Packages a production build of the application
    cmds:
      - task: '{{if eq .PLATFORM "darwin/universal"}}darwin:package:universal{{else}}{{OS}}:package{{end}}'

  run:
    desc: Runs the application
    cmds:
      - task: "{{OS}}:run"

  test:
    desc: Runs tests
    deps:
      - task: dev:gen:mocks
    preconditions:
      - mkdir -p frontend/dist
      - touch frontend/dist/index.html
    cmds:
      - go test -cover -mod=readonly --timeout 1m $(go list ./... | grep -v ent)
