// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as timestamppb$0 from "../../../../../../google.golang.org/protobuf/types/known/timestamppb/models.js";

/**
 * LoginResponse contains the result of a login initiation.
 */
export class LoginResponse {
    /**
     * Whether the email was successfully sent.
     */
    "sent"?: boolean;

    /**
     * Unique session identifier for this authentication attempt.
     * Use this with WaitForAuthentication.
     */
    "session_id"?: string;

    /**
     * When the authentication session expires.
     */
    "expires_at"?: timestamppb$0.Timestamp | null;

    /** Creates a new LoginResponse instance. */
    constructor($$source: Partial<LoginResponse> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): LoginResponse {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("expires_at" in $$parsedSource) {
            $$parsedSource["expires_at"] = $$createField2_0($$parsedSource["expires_at"]);
        }
        return new LoginResponse($$parsedSource as Partial<LoginResponse>);
    }
}

/**
 * RegisterResponse contains the result of a registration initiation.
 */
export class RegisterResponse {
    /**
     * Whether the email was successfully sent.
     */
    "sent"?: boolean;

    /**
     * Unique session identifier for this authentication attempt.
     * Use this with WaitForAuthentication.
     */
    "session_id"?: string;

    /**
     * When the authentication session expires.
     */
    "expires_at"?: timestamppb$0.Timestamp | null;

    /** Creates a new RegisterResponse instance. */
    constructor($$source: Partial<RegisterResponse> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegisterResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): RegisterResponse {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("expires_at" in $$parsedSource) {
            $$parsedSource["expires_at"] = $$createField2_0($$parsedSource["expires_at"]);
        }
        return new RegisterResponse($$parsedSource as Partial<RegisterResponse>);
    }
}

// Private type creation functions
const $$createType0 = timestamppb$0.Timestamp.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
