// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Action defines the type for the "action" enum field.
 */
export enum Action {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Action values.
     */
    ActionUnlockRepository = "unlockRepository",
};

/**
 * Type defines the type for the "type" enum field.
 */
export enum Type {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Type values.
     */
    TypeFailedBackupRun = "failed_backup_run",
    TypeFailedPruningRun = "failed_pruning_run",
    TypeWarningBackupRun = "warning_backup_run",
    TypeWarningPruningRun = "warning_pruning_run",
    TypeFailedQuickCheck = "failed_quick_check",
    TypeFailedFullCheck = "failed_full_check",
    TypeWarningQuickCheck = "warning_quick_check",
    TypeWarningFullCheck = "warning_full_check",
};
