// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backupprofile$0 from "./backupprofile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backupschedule$0 from "./backupschedule/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cloudrepository$0 from "./cloudrepository/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notification$0 from "./notification/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "./settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Archive is the model entity for the Archive schema.
 */
export class Archive {
    /**
     * ID of the ent.
     */
    "id": number;

    /**
     * CreatedAt holds the value of the "created_at" field.
     */
    "createdAt": time$0.Time;

    /**
     * UpdatedAt holds the value of the "updated_at" field.
     */
    "updatedAt": time$0.Time;

    /**
     * Name holds the value of the "name" field.
     */
    "name": string;

    /**
     * Duration holds the value of the "duration" field.
     */
    "duration": number;

    /**
     * BorgID holds the value of the "borg_id" field.
     */
    "borgId": string;

    /**
     * WillBePruned holds the value of the "will_be_pruned" field.
     */
    "willBePruned": boolean;

    /**
     * Comment stored with the archive in borg
     */
    "comment": string;

    /**
     * Edges holds the relations/edges for other nodes in the graph.
     * The values are being populated by the ArchiveQuery when eager-loading is set.
     */
    "edges": ArchiveEdges;

    /** Creates a new Archive instance. */
    constructor($$source: Partial<Archive> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("borgId" in $$source)) {
            this["borgId"] = "";
        }
        if (!("willBePruned" in $$source)) {
            this["willBePruned"] = false;
        }
        if (!("comment" in $$source)) {
            this["comment"] = "";
        }
        if (!("edges" in $$source)) {
            this["edges"] = (new ArchiveEdges());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Archive instance from a string or object.
     */
    static createFrom($$source: any = {}): Archive {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField8_0($$parsedSource["edges"]);
        }
        return new Archive($$parsedSource as Partial<Archive>);
    }
}

/**
 * ArchiveEdges holds the relations/edges for other nodes in the graph.
 */
export class ArchiveEdges {
    /**
     * Repository holds the value of the repository edge.
     */
    "repository"?: Repository | null;

    /**
     * BackupProfile holds the value of the backup_profile edge.
     */
    "backupProfile"?: BackupProfile | null;

    /** Creates a new ArchiveEdges instance. */
    constructor($$source: Partial<ArchiveEdges> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchiveEdges instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchiveEdges {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("repository" in $$parsedSource) {
            $$parsedSource["repository"] = $$createField0_0($$parsedSource["repository"]);
        }
        if ("backupProfile" in $$parsedSource) {
            $$parsedSource["backupProfile"] = $$createField1_0($$parsedSource["backupProfile"]);
        }
        return new ArchiveEdges($$parsedSource as Partial<ArchiveEdges>);
    }
}

/**
 * BackupProfile is the model entity for the BackupProfile schema.
 */
export class BackupProfile {
    /**
     * ID of the ent.
     */
    "id": number;

    /**
     * CreatedAt holds the value of the "created_at" field.
     */
    "createdAt": time$0.Time;

    /**
     * UpdatedAt holds the value of the "updated_at" field.
     */
    "updatedAt": time$0.Time;

    /**
     * Name holds the value of the "name" field.
     */
    "name": string;

    /**
     * Prefix holds the value of the "prefix" field.
     */
    "prefix": string;

    /**
     * BackupPaths holds the value of the "backup_paths" field.
     */
    "backupPaths": string[];

    /**
     * ExcludePaths holds the value of the "exclude_paths" field.
     */
    "excludePaths": string[];

    /**
     * Exclude directories containing CACHEDIR.TAG file
     */
    "excludeCaches": boolean;

    /**
     * Icon holds the value of the "icon" field.
     */
    "icon": backupprofile$0.Icon;

    /**
     * Compression algorithm for backups
     */
    "compressionMode": backupprofile$0.CompressionMode;

    /**
     * Compression level (algorithm-specific range)
     */
    "compressionLevel": number | null;

    /**
     * DataSectionCollapsed holds the value of the "data_section_collapsed" field.
     */
    "dataSectionCollapsed": boolean;

    /**
     * ScheduleSectionCollapsed holds the value of the "schedule_section_collapsed" field.
     */
    "scheduleSectionCollapsed": boolean;

    /**
     * UI state: whether advanced settings section is collapsed
     */
    "advancedSectionCollapsed": boolean;

    /**
     * Edges holds the relations/edges for other nodes in the graph.
     * The values are being populated by the BackupProfileQuery when eager-loading is set.
     */
    "edges": BackupProfileEdges;

    /** Creates a new BackupProfile instance. */
    constructor($$source: Partial<BackupProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("backupPaths" in $$source)) {
            this["backupPaths"] = [];
        }
        if (!("excludePaths" in $$source)) {
            this["excludePaths"] = [];
        }
        if (!("excludeCaches" in $$source)) {
            this["excludeCaches"] = false;
        }
        if (!("icon" in $$source)) {
            this["icon"] = backupprofile$0.Icon.$zero;
        }
        if (!("compressionMode" in $$source)) {
            this["compressionMode"] = backupprofile$0.CompressionMode.$zero;
        }
        if (!("compressionLevel" in $$source)) {
            this["compressionLevel"] = null;
        }
        if (!("dataSectionCollapsed" in $$source)) {
            this["dataSectionCollapsed"] = false;
        }
        if (!("scheduleSectionCollapsed" in $$source)) {
            this["scheduleSectionCollapsed"] = false;
        }
        if (!("advancedSectionCollapsed" in $$source)) {
            this["advancedSectionCollapsed"] = false;
        }
        if (!("edges" in $$source)) {
            this["edges"] = (new BackupProfileEdges());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupProfile {
        const $$createField5_0 = $$createType5;
        const $$createField6_0 = $$createType5;
        const $$createField14_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("backupPaths" in $$parsedSource) {
            $$parsedSource["backupPaths"] = $$createField5_0($$parsedSource["backupPaths"]);
        }
        if ("excludePaths" in $$parsedSource) {
            $$parsedSource["excludePaths"] = $$createField6_0($$parsedSource["excludePaths"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField14_0($$parsedSource["edges"]);
        }
        return new BackupProfile($$parsedSource as Partial<BackupProfile>);
    }
}

/**
 * BackupProfileEdges holds the relations/edges for other nodes in the graph.
 */
export class BackupProfileEdges {
    /**
     * Repositories holds the value of the repositories edge.
     */
    "repositories"?: (Repository | null)[];

    /**
     * Archives holds the value of the archives edge.
     */
    "archives"?: (Archive | null)[];

    /**
     * BackupSchedule holds the value of the backup_schedule edge.
     */
    "backupSchedule"?: BackupSchedule | null;

    /**
     * PruningRule holds the value of the pruning_rule edge.
     */
    "pruningRule"?: PruningRule | null;

    /**
     * Notifications holds the value of the notifications edge.
     */
    "notifications"?: (Notification | null)[];

    /** Creates a new BackupProfileEdges instance. */
    constructor($$source: Partial<BackupProfileEdges> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupProfileEdges instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupProfileEdges {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType10;
        const $$createField2_0 = $$createType12;
        const $$createField3_0 = $$createType14;
        const $$createField4_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("repositories" in $$parsedSource) {
            $$parsedSource["repositories"] = $$createField0_0($$parsedSource["repositories"]);
        }
        if ("archives" in $$parsedSource) {
            $$parsedSource["archives"] = $$createField1_0($$parsedSource["archives"]);
        }
        if ("backupSchedule" in $$parsedSource) {
            $$parsedSource["backupSchedule"] = $$createField2_0($$parsedSource["backupSchedule"]);
        }
        if ("pruningRule" in $$parsedSource) {
            $$parsedSource["pruningRule"] = $$createField3_0($$parsedSource["pruningRule"]);
        }
        if ("notifications" in $$parsedSource) {
            $$parsedSource["notifications"] = $$createField4_0($$parsedSource["notifications"]);
        }
        return new BackupProfileEdges($$parsedSource as Partial<BackupProfileEdges>);
    }
}

/**
 * BackupSchedule is the model entity for the BackupSchedule schema.
 */
export class BackupSchedule {
    /**
     * ID of the ent.
     */
    "id": number;

    /**
     * CreatedAt holds the value of the "created_at" field.
     */
    "createdAt": time$0.Time;

    /**
     * UpdatedAt holds the value of the "updated_at" field.
     */
    "updatedAt": time$0.Time;

    /**
     * Mode holds the value of the "mode" field.
     */
    "mode": backupschedule$0.Mode;

    /**
     * DailyAt holds the value of the "daily_at" field.
     */
    "dailyAt": time$0.Time;

    /**
     * Weekday holds the value of the "weekday" field.
     */
    "weekday": backupschedule$0.Weekday;

    /**
     * WeeklyAt holds the value of the "weekly_at" field.
     */
    "weeklyAt": time$0.Time;

    /**
     * Monthday holds the value of the "monthday" field.
     */
    "monthday": number;

    /**
     * MonthlyAt holds the value of the "monthly_at" field.
     */
    "monthlyAt": time$0.Time;

    /**
     * NextRun holds the value of the "next_run" field.
     */
    "nextRun": time$0.Time;

    /**
     * LastRun holds the value of the "last_run" field.
     */
    "lastRun": time$0.Time | null;

    /**
     * LastRunStatus holds the value of the "last_run_status" field.
     */
    "lastRunStatus": string | null;

    /**
     * Edges holds the relations/edges for other nodes in the graph.
     * The values are being populated by the BackupScheduleQuery when eager-loading is set.
     */
    "edges": BackupScheduleEdges;

    /** Creates a new BackupSchedule instance. */
    constructor($$source: Partial<BackupSchedule> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("mode" in $$source)) {
            this["mode"] = backupschedule$0.Mode.$zero;
        }
        if (!("dailyAt" in $$source)) {
            this["dailyAt"] = null;
        }
        if (!("weekday" in $$source)) {
            this["weekday"] = backupschedule$0.Weekday.$zero;
        }
        if (!("weeklyAt" in $$source)) {
            this["weeklyAt"] = null;
        }
        if (!("monthday" in $$source)) {
            this["monthday"] = 0;
        }
        if (!("monthlyAt" in $$source)) {
            this["monthlyAt"] = null;
        }
        if (!("nextRun" in $$source)) {
            this["nextRun"] = null;
        }
        if (!("lastRun" in $$source)) {
            this["lastRun"] = null;
        }
        if (!("lastRunStatus" in $$source)) {
            this["lastRunStatus"] = null;
        }
        if (!("edges" in $$source)) {
            this["edges"] = (new BackupScheduleEdges());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupSchedule instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupSchedule {
        const $$createField12_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField12_0($$parsedSource["edges"]);
        }
        return new BackupSchedule($$parsedSource as Partial<BackupSchedule>);
    }
}

/**
 * BackupScheduleEdges holds the relations/edges for other nodes in the graph.
 */
export class BackupScheduleEdges {
    /**
     * BackupProfile holds the value of the backup_profile edge.
     */
    "backupProfile"?: BackupProfile | null;

    /** Creates a new BackupScheduleEdges instance. */
    constructor($$source: Partial<BackupScheduleEdges> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupScheduleEdges instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupScheduleEdges {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("backupProfile" in $$parsedSource) {
            $$parsedSource["backupProfile"] = $$createField0_0($$parsedSource["backupProfile"]);
        }
        return new BackupScheduleEdges($$parsedSource as Partial<BackupScheduleEdges>);
    }
}

/**
 * CloudRepository is the model entity for the CloudRepository schema.
 */
export class CloudRepository {
    /**
     * ID of the ent.
     */
    "id": number;

    /**
     * CreatedAt holds the value of the "created_at" field.
     */
    "createdAt": time$0.Time;

    /**
     * UpdatedAt holds the value of the "updated_at" field.
     */
    "updatedAt": time$0.Time;

    /**
     * CloudID holds the value of the "cloud_id" field.
     */
    "cloudId": string;

    /**
     * StorageUsedBytes holds the value of the "storage_used_bytes" field.
     */
    "storageUsedBytes": number;

    /**
     * Location holds the value of the "location" field.
     */
    "location": cloudrepository$0.Location;

    /**
     * Edges holds the relations/edges for other nodes in the graph.
     * The values are being populated by the CloudRepositoryQuery when eager-loading is set.
     */
    "edges": CloudRepositoryEdges;

    /** Creates a new CloudRepository instance. */
    constructor($$source: Partial<CloudRepository> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("cloudId" in $$source)) {
            this["cloudId"] = "";
        }
        if (!("storageUsedBytes" in $$source)) {
            this["storageUsedBytes"] = 0;
        }
        if (!("location" in $$source)) {
            this["location"] = cloudrepository$0.Location.$zero;
        }
        if (!("edges" in $$source)) {
            this["edges"] = (new CloudRepositoryEdges());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloudRepository instance from a string or object.
     */
    static createFrom($$source: any = {}): CloudRepository {
        const $$createField6_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField6_0($$parsedSource["edges"]);
        }
        return new CloudRepository($$parsedSource as Partial<CloudRepository>);
    }
}

/**
 * CloudRepositoryEdges holds the relations/edges for other nodes in the graph.
 */
export class CloudRepositoryEdges {
    /**
     * Repository holds the value of the repository edge.
     */
    "repository": Repository | null;

    /** Creates a new CloudRepositoryEdges instance. */
    constructor($$source: Partial<CloudRepositoryEdges> = {}) {
        if (!("repository" in $$source)) {
            this["repository"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloudRepositoryEdges instance from a string or object.
     */
    static createFrom($$source: any = {}): CloudRepositoryEdges {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("repository" in $$parsedSource) {
            $$parsedSource["repository"] = $$createField0_0($$parsedSource["repository"]);
        }
        return new CloudRepositoryEdges($$parsedSource as Partial<CloudRepositoryEdges>);
    }
}

/**
 * Notification is the model entity for the Notification schema.
 */
export class Notification {
    /**
     * ID of the ent.
     */
    "id": number;

    /**
     * CreatedAt holds the value of the "created_at" field.
     */
    "createdAt": time$0.Time;

    /**
     * UpdatedAt holds the value of the "updated_at" field.
     */
    "updatedAt": time$0.Time;

    /**
     * Message holds the value of the "message" field.
     */
    "message": string;

    /**
     * Type holds the value of the "type" field.
     */
    "type": notification$0.Type;

    /**
     * Seen holds the value of the "seen" field.
     */
    "seen": boolean;

    /**
     * Action holds the value of the "action" field.
     */
    "action": notification$0.Action;

    /**
     * Edges holds the relations/edges for other nodes in the graph.
     * The values are being populated by the NotificationQuery when eager-loading is set.
     */
    "edges": NotificationEdges;

    /** Creates a new Notification instance. */
    constructor($$source: Partial<Notification> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = notification$0.Type.$zero;
        }
        if (!("seen" in $$source)) {
            this["seen"] = false;
        }
        if (!("action" in $$source)) {
            this["action"] = notification$0.Action.$zero;
        }
        if (!("edges" in $$source)) {
            this["edges"] = (new NotificationEdges());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Notification instance from a string or object.
     */
    static createFrom($$source: any = {}): Notification {
        const $$createField7_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField7_0($$parsedSource["edges"]);
        }
        return new Notification($$parsedSource as Partial<Notification>);
    }
}

/**
 * NotificationEdges holds the relations/edges for other nodes in the graph.
 */
export class NotificationEdges {
    /**
     * BackupProfile holds the value of the backup_profile edge.
     */
    "backupProfile"?: BackupProfile | null;

    /**
     * Repository holds the value of the repository edge.
     */
    "repository"?: Repository | null;

    /** Creates a new NotificationEdges instance. */
    constructor($$source: Partial<NotificationEdges> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotificationEdges instance from a string or object.
     */
    static createFrom($$source: any = {}): NotificationEdges {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("backupProfile" in $$parsedSource) {
            $$parsedSource["backupProfile"] = $$createField0_0($$parsedSource["backupProfile"]);
        }
        if ("repository" in $$parsedSource) {
            $$parsedSource["repository"] = $$createField1_0($$parsedSource["repository"]);
        }
        return new NotificationEdges($$parsedSource as Partial<NotificationEdges>);
    }
}

/**
 * PruningRule is the model entity for the PruningRule schema.
 */
export class PruningRule {
    /**
     * ID of the ent.
     */
    "id": number;

    /**
     * CreatedAt holds the value of the "created_at" field.
     */
    "createdAt": time$0.Time;

    /**
     * UpdatedAt holds the value of the "updated_at" field.
     */
    "updatedAt": time$0.Time;

    /**
     * IsEnabled holds the value of the "is_enabled" field.
     */
    "isEnabled": boolean;

    /**
     * KeepHourly holds the value of the "keep_hourly" field.
     */
    "keepHourly": number;

    /**
     * KeepDaily holds the value of the "keep_daily" field.
     */
    "keepDaily": number;

    /**
     * KeepWeekly holds the value of the "keep_weekly" field.
     */
    "keepWeekly": number;

    /**
     * KeepMonthly holds the value of the "keep_monthly" field.
     */
    "keepMonthly": number;

    /**
     * KeepYearly holds the value of the "keep_yearly" field.
     */
    "keepYearly": number;

    /**
     * KeepWithinDays holds the value of the "keep_within_days" field.
     */
    "keepWithinDays": number;

    /**
     * NextRun holds the value of the "next_run" field.
     */
    "nextRun": time$0.Time;

    /**
     * LastRun holds the value of the "last_run" field.
     */
    "lastRun": time$0.Time | null;

    /**
     * LastRunStatus holds the value of the "last_run_status" field.
     */
    "lastRunStatus": string | null;

    /**
     * Edges holds the relations/edges for other nodes in the graph.
     * The values are being populated by the PruningRuleQuery when eager-loading is set.
     */
    "edges": PruningRuleEdges;

    /** Creates a new PruningRule instance. */
    constructor($$source: Partial<PruningRule> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("isEnabled" in $$source)) {
            this["isEnabled"] = false;
        }
        if (!("keepHourly" in $$source)) {
            this["keepHourly"] = 0;
        }
        if (!("keepDaily" in $$source)) {
            this["keepDaily"] = 0;
        }
        if (!("keepWeekly" in $$source)) {
            this["keepWeekly"] = 0;
        }
        if (!("keepMonthly" in $$source)) {
            this["keepMonthly"] = 0;
        }
        if (!("keepYearly" in $$source)) {
            this["keepYearly"] = 0;
        }
        if (!("keepWithinDays" in $$source)) {
            this["keepWithinDays"] = 0;
        }
        if (!("nextRun" in $$source)) {
            this["nextRun"] = null;
        }
        if (!("lastRun" in $$source)) {
            this["lastRun"] = null;
        }
        if (!("lastRunStatus" in $$source)) {
            this["lastRunStatus"] = null;
        }
        if (!("edges" in $$source)) {
            this["edges"] = (new PruningRuleEdges());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PruningRule instance from a string or object.
     */
    static createFrom($$source: any = {}): PruningRule {
        const $$createField13_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField13_0($$parsedSource["edges"]);
        }
        return new PruningRule($$parsedSource as Partial<PruningRule>);
    }
}

/**
 * PruningRuleEdges holds the relations/edges for other nodes in the graph.
 */
export class PruningRuleEdges {
    /**
     * BackupProfile holds the value of the backup_profile edge.
     */
    "backupProfile"?: BackupProfile | null;

    /** Creates a new PruningRuleEdges instance. */
    constructor($$source: Partial<PruningRuleEdges> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PruningRuleEdges instance from a string or object.
     */
    static createFrom($$source: any = {}): PruningRuleEdges {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("backupProfile" in $$parsedSource) {
            $$parsedSource["backupProfile"] = $$createField0_0($$parsedSource["backupProfile"]);
        }
        return new PruningRuleEdges($$parsedSource as Partial<PruningRuleEdges>);
    }
}

/**
 * Repository is the model entity for the Repository schema.
 */
export class Repository {
    /**
     * ID of the ent.
     */
    "id": number;

    /**
     * CreatedAt holds the value of the "created_at" field.
     */
    "createdAt": time$0.Time;

    /**
     * UpdatedAt holds the value of the "updated_at" field.
     */
    "updatedAt": time$0.Time;

    /**
     * Name holds the value of the "name" field.
     */
    "name": string;

    /**
     * URL holds the value of the "url" field.
     */
    "url": string;

    /**
     * Password holds the value of the "password" field.
     */
    "password": string;

    /**
     * Timestamp of last quick check (--repository-only)
     */
    "lastQuickCheckAt": time$0.Time | null;

    /**
     * Error messages from last quick check, empty array if successful
     */
    "quickCheckError": string[];

    /**
     * Timestamp of last full check (--verify-data)
     */
    "lastFullCheckAt": time$0.Time | null;

    /**
     * Error messages from last full check, empty array if successful
     */
    "fullCheckError": string[];

    /**
     * Total number of all chunks across all archives (including duplicates)
     */
    "statsTotalChunks": number;

    /**
     * Total uncompressed size of all chunks multiplied by their reference counts
     */
    "statsTotalSize": number;

    /**
     * Total compressed size of all chunks multiplied by their reference counts (on-disk footprint with references)
     */
    "statsTotalCsize": number;

    /**
     * Number of unique/deduplicated chunks
     */
    "statsTotalUniqueChunks": number;

    /**
     * Uncompressed size of unique chunks only (raw deduplicated data volume)
     */
    "statsUniqueSize": number;

    /**
     * Compressed size of unique chunks only (actual storage consumed on disk)
     */
    "statsUniqueCsize": number;

    /**
     * Edges holds the relations/edges for other nodes in the graph.
     * The values are being populated by the RepositoryQuery when eager-loading is set.
     */
    "edges": RepositoryEdges;

    /** Creates a new Repository instance. */
    constructor($$source: Partial<Repository> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("lastQuickCheckAt" in $$source)) {
            this["lastQuickCheckAt"] = null;
        }
        if (!("quickCheckError" in $$source)) {
            this["quickCheckError"] = [];
        }
        if (!("lastFullCheckAt" in $$source)) {
            this["lastFullCheckAt"] = null;
        }
        if (!("fullCheckError" in $$source)) {
            this["fullCheckError"] = [];
        }
        if (!("statsTotalChunks" in $$source)) {
            this["statsTotalChunks"] = 0;
        }
        if (!("statsTotalSize" in $$source)) {
            this["statsTotalSize"] = 0;
        }
        if (!("statsTotalCsize" in $$source)) {
            this["statsTotalCsize"] = 0;
        }
        if (!("statsTotalUniqueChunks" in $$source)) {
            this["statsTotalUniqueChunks"] = 0;
        }
        if (!("statsUniqueSize" in $$source)) {
            this["statsUniqueSize"] = 0;
        }
        if (!("statsUniqueCsize" in $$source)) {
            this["statsUniqueCsize"] = 0;
        }
        if (!("edges" in $$source)) {
            this["edges"] = (new RepositoryEdges());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Repository instance from a string or object.
     */
    static createFrom($$source: any = {}): Repository {
        const $$createField7_0 = $$createType5;
        const $$createField9_0 = $$createType5;
        const $$createField16_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("quickCheckError" in $$parsedSource) {
            $$parsedSource["quickCheckError"] = $$createField7_0($$parsedSource["quickCheckError"]);
        }
        if ("fullCheckError" in $$parsedSource) {
            $$parsedSource["fullCheckError"] = $$createField9_0($$parsedSource["fullCheckError"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField16_0($$parsedSource["edges"]);
        }
        return new Repository($$parsedSource as Partial<Repository>);
    }
}

/**
 * RepositoryEdges holds the relations/edges for other nodes in the graph.
 */
export class RepositoryEdges {
    /**
     * BackupProfiles holds the value of the backup_profiles edge.
     */
    "backupProfiles"?: (BackupProfile | null)[];

    /**
     * Archives holds the value of the archives edge.
     */
    "archives"?: (Archive | null)[];

    /**
     * Notifications holds the value of the notifications edge.
     */
    "notifications"?: (Notification | null)[];

    /**
     * CloudRepository holds the value of the cloud_repository edge.
     */
    "cloudRepository"?: CloudRepository | null;

    /** Creates a new RepositoryEdges instance. */
    constructor($$source: Partial<RepositoryEdges> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepositoryEdges instance from a string or object.
     */
    static createFrom($$source: any = {}): RepositoryEdges {
        const $$createField0_0 = $$createType23;
        const $$createField1_0 = $$createType10;
        const $$createField2_0 = $$createType17;
        const $$createField3_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("backupProfiles" in $$parsedSource) {
            $$parsedSource["backupProfiles"] = $$createField0_0($$parsedSource["backupProfiles"]);
        }
        if ("archives" in $$parsedSource) {
            $$parsedSource["archives"] = $$createField1_0($$parsedSource["archives"]);
        }
        if ("notifications" in $$parsedSource) {
            $$parsedSource["notifications"] = $$createField2_0($$parsedSource["notifications"]);
        }
        if ("cloudRepository" in $$parsedSource) {
            $$parsedSource["cloudRepository"] = $$createField3_0($$parsedSource["cloudRepository"]);
        }
        return new RepositoryEdges($$parsedSource as Partial<RepositoryEdges>);
    }
}

/**
 * Settings is the model entity for the Settings schema.
 */
export class Settings {
    /**
     * ID of the ent.
     */
    "id"?: number;

    /**
     * CreatedAt holds the value of the "created_at" field.
     */
    "createdAt": time$0.Time;

    /**
     * UpdatedAt holds the value of the "updated_at" field.
     */
    "updatedAt": time$0.Time;

    /**
     * ShowWelcome holds the value of the "show_welcome" field.
     */
    "showWelcome": boolean;

    /**
     * ExpertMode holds the value of the "expert_mode" field.
     */
    "expertMode": boolean;

    /**
     * Theme holds the value of the "theme" field.
     */
    "theme"?: settings$0.Theme;

    /**
     * DisableTransitions holds the value of the "disable_transitions" field.
     */
    "disableTransitions": boolean;

    /**
     * DisableShadows holds the value of the "disable_shadows" field.
     */
    "disableShadows": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("showWelcome" in $$source)) {
            this["showWelcome"] = false;
        }
        if (!("expertMode" in $$source)) {
            this["expertMode"] = false;
        }
        if (!("disableTransitions" in $$source)) {
            this["disableTransitions"] = false;
        }
        if (!("disableShadows" in $$source)) {
            this["disableShadows"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = ArchiveEdges.createFrom;
const $$createType1 = Repository.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = BackupProfile.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = BackupProfileEdges.createFrom;
const $$createType7 = $Create.Array($$createType2);
const $$createType8 = Archive.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = BackupSchedule.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = PruningRule.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = Notification.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = BackupScheduleEdges.createFrom;
const $$createType19 = CloudRepositoryEdges.createFrom;
const $$createType20 = NotificationEdges.createFrom;
const $$createType21 = PruningRuleEdges.createFrom;
const $$createType22 = RepositoryEdges.createFrom;
const $$createType23 = $Create.Array($$createType4);
const $$createType24 = CloudRepository.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
