// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service contains the business logic and provides methods exposed to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as arcov1$0 from "../../api/v1/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ent$0 from "../../ent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "../../platform/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbortBackup immediately aborts a running backup operation
 */
export function AbortBackup(backupId: types$0.BackupId): $CancellablePromise<void> {
    return $Call.ByID(1933267942, backupId);
}

/**
 * AbortBackups aborts multiple running backup operations
 */
export function AbortBackups(backupIds: types$0.BackupId[]): $CancellablePromise<void> {
    return $Call.ByID(4217672591, backupIds);
}

/**
 * All retrieves all repositories
 */
export function All(): $CancellablePromise<($models.Repository | null)[]> {
    return $Call.ByID(593256237).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * AllWithQueue retrieves all repositories with queue information
 */
export function AllWithQueue(): $CancellablePromise<($models.RepositoryWithQueue | null)[]> {
    return $Call.ByID(2041334972).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * BreakLock breaks a repository lock
 */
export function BreakLock(repoId: number): $CancellablePromise<void> {
    return $Call.ByID(4281482770, repoId);
}

/**
 * CancelOperation cancels a queued or running operation
 */
export function CancelOperation(operationId: string): $CancellablePromise<void> {
    return $Call.ByID(3062607757, operationId);
}

/**
 * ChangePassword changes the password for a repository
 */
export function ChangePassword(repoId: number, password: string): $CancellablePromise<void> {
    return $Call.ByID(2850019591, repoId, password);
}

/**
 * Create creates a new repository
 */
export function Create(name: string, location: string, password: string, noPassword: boolean): $CancellablePromise<$models.Repository | null> {
    return $Call.ByID(3296679418, name, location, password, noPassword).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateCloudRepository creates a new ArcoCloud repository
 */
export function CreateCloudRepository(name: string, password: string, location: arcov1$0.RepositoryLocation): $CancellablePromise<$models.Repository | null> {
    return $Call.ByID(2968644739, name, password, location).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Delete deletes a repository completely. This cancels all other operations
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(1592048265, id);
}

/**
 * ExaminePrunes analyzes what would be pruned with given rules
 */
export function ExaminePrunes(backupProfileId: number, pruningRule: ent$0.PruningRule | null, saveResults: boolean): $CancellablePromise<$models.ExaminePruningResult[]> {
    return $Call.ByID(166629156, backupProfileId, pruningRule, saveResults).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * Get retrieves a repository by ID
 */
export function Get(repoId: number): $CancellablePromise<$models.Repository | null> {
    return $Call.ByID(2350435594, repoId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetArchive retrieves an archive by ID
 */
export function GetArchive(id: number): $CancellablePromise<ent$0.Archive | null> {
    return $Call.ByID(3790326640, id).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetBackupProfilesThatHaveOnlyRepo gets backup profiles that only have this repo
 */
export function GetBackupProfilesThatHaveOnlyRepo(repoId: number): $CancellablePromise<(ent$0.BackupProfile | null)[]> {
    return $Call.ByID(2432944859, repoId).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetByBackupId retrieves a repository by backup ID
 */
export function GetByBackupId(bId: types$0.BackupId): $CancellablePromise<$models.Repository | null> {
    return $Call.ByID(1062575188, bId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetLastArchiveByRepoId gets last archive for repository
 */
export function GetLastArchiveByRepoId(repoId: number): $CancellablePromise<ent$0.Archive | null> {
    return $Call.ByID(3556071828, repoId).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetOperation retrieves an operation by ID
 */
export function GetOperation(operationId: string): $CancellablePromise<$models.QueuedOperation | null> {
    return $Call.ByID(3469297119, operationId).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetOperationsByStatus returns operations filtered by status for a repository
 */
export function GetOperationsByStatus(repoId: number, status: $models.OperationStatusType): $CancellablePromise<($models.QueuedOperation | null)[]> {
    return $Call.ByID(2513578131, repoId, status).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * GetPaginatedArchives retrieves paginated archives for a repository
 */
export function GetPaginatedArchives(req: $models.PaginatedArchivesRequest | null): $CancellablePromise<$models.PaginatedArchivesResponse | null> {
    return $Call.ByID(3644900762, req).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * GetPruningDates retrieves pruning dates for specified archives
 */
export function GetPruningDates(archiveIds: number[]): $CancellablePromise<$models.PruningDates> {
    return $Call.ByID(2102076250, archiveIds).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * GetQueuedOperations returns all operations for a repository
 */
export function GetQueuedOperations(repoId: number): $CancellablePromise<($models.QueuedOperation | null)[]> {
    return $Call.ByID(1376269121, repoId).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * GetWithQueue retrieves a repository with queue information
 */
export function GetWithQueue(repoId: number): $CancellablePromise<$models.RepositoryWithQueue | null> {
    return $Call.ByID(144266353, repoId).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * IsBorgRepository checks if a path contains a borg repository
 */
export function IsBorgRepository(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(101129870, path);
}

/**
 * Mount mounts a repository
 */
export function Mount(repoId: number): $CancellablePromise<platform$0.MountState | null> {
    return $Call.ByID(967190463, repoId).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * MountArchive mounts a specific archive
 */
export function MountArchive(archiveId: number): $CancellablePromise<platform$0.MountState | null> {
    return $Call.ByID(1226599023, archiveId).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * QueueArchiveDelete queues an archive deletion operation
 */
export function QueueArchiveDelete(archiveId: number): $CancellablePromise<string> {
    return $Call.ByID(3548195286, archiveId);
}

/**
 * QueueArchiveRefresh queues an archive refresh operation
 */
export function QueueArchiveRefresh(repoId: number): $CancellablePromise<string> {
    return $Call.ByID(2157976592, repoId);
}

/**
 * QueueArchiveRename queues an archive rename operation
 */
export function QueueArchiveRename(archiveId: number, prefix: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(4267028159, archiveId, prefix, name);
}

/**
 * QueueBackup queues a backup operation
 */
export function QueueBackup(backupId: types$0.BackupId): $CancellablePromise<string> {
    return $Call.ByID(875725915, backupId);
}

/**
 * QueueBackups queues multiple backup operations (convenience method)
 */
export function QueueBackups(backupIds: types$0.BackupId[]): $CancellablePromise<string[]> {
    return $Call.ByID(1401293560, backupIds).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * QueuePrune queues a prune operation
 */
export function QueuePrune(backupId: types$0.BackupId): $CancellablePromise<string> {
    return $Call.ByID(295202139, backupId);
}

/**
 * RegenerateSSHKey regenerates SSH key for ArcoCloud repositories
 */
export function RegenerateSSHKey(): $CancellablePromise<void> {
    return $Call.ByID(3683576253);
}

/**
 * Remove removes a repository from database only (does not delete physical repo)
 */
export function Remove(id: number): $CancellablePromise<void> {
    return $Call.ByID(2560302714, id);
}

/**
 * TestRepoConnection tests connection to a repository
 */
export function TestRepoConnection(path: string, password: string): $CancellablePromise<$models.TestRepoConnectionResult> {
    return $Call.ByID(1151269054, path, password).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * Unmount unmounts a repository
 */
export function Unmount(repoId: number): $CancellablePromise<platform$0.MountState | null> {
    return $Call.ByID(3507624802, repoId).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * UnmountAllForRepos unmounts all mounts for specified repositories
 */
export function UnmountAllForRepos(repoIds: number[]): $CancellablePromise<void> {
    return $Call.ByID(1105783937, repoIds);
}

/**
 * UnmountArchive unmounts a specific archive
 */
export function UnmountArchive(archiveId: number): $CancellablePromise<platform$0.MountState | null> {
    return $Call.ByID(2999465112, archiveId).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * Update updates a repository with provided changes
 */
export function Update(repoId: number, updateReq: $models.UpdateRequest | null): $CancellablePromise<$models.Repository | null> {
    return $Call.ByID(3450666087, repoId, updateReq).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ValidateArchiveName validates an archive name
 */
export function ValidateArchiveName(archiveId: number, prefix: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(392924285, archiveId, prefix, name);
}

/**
 * ValidateRepoName validates a repository name
 */
export function ValidateRepoName(name: string): $CancellablePromise<string> {
    return $Call.ByID(3060066791, name);
}

/**
 * ValidateRepoPath validates a repository path
 */
export function ValidateRepoPath(path: string, isLocal: boolean): $CancellablePromise<string> {
    return $Call.ByID(2882211019, path, isLocal);
}

// Private type creation functions
const $$createType0 = $models.Repository.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.RepositoryWithQueue.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.ExaminePruningResult.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = ent$0.Archive.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = ent$0.BackupProfile.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.QueuedOperation.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.PaginatedArchivesResponse.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $models.PruningDates.createFrom;
const $$createType19 = platform$0.MountState.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = $Create.Array($Create.Any);
const $$createType22 = $models.TestRepoConnectionResult.createFrom;
