// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loomi-labs/arco/backend/ent/cloudrepository"
	"github.com/loomi-labs/arco/backend/ent/predicate"
	"github.com/loomi-labs/arco/backend/ent/repository"
)

// CloudRepositoryQuery is the builder for querying CloudRepository entities.
type CloudRepositoryQuery struct {
	config
	ctx            *QueryContext
	order          []cloudrepository.OrderOption
	inters         []Interceptor
	predicates     []predicate.CloudRepository
	withRepository *RepositoryQuery
	modifiers      []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CloudRepositoryQuery builder.
func (_q *CloudRepositoryQuery) Where(ps ...predicate.CloudRepository) *CloudRepositoryQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CloudRepositoryQuery) Limit(limit int) *CloudRepositoryQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CloudRepositoryQuery) Offset(offset int) *CloudRepositoryQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CloudRepositoryQuery) Unique(unique bool) *CloudRepositoryQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CloudRepositoryQuery) Order(o ...cloudrepository.OrderOption) *CloudRepositoryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRepository chains the current query on the "repository" edge.
func (_q *CloudRepositoryQuery) QueryRepository() *RepositoryQuery {
	query := (&RepositoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cloudrepository.Table, cloudrepository.FieldID, selector),
			sqlgraph.To(repository.Table, repository.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, cloudrepository.RepositoryTable, cloudrepository.RepositoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CloudRepository entity from the query.
// Returns a *NotFoundError when no CloudRepository was found.
func (_q *CloudRepositoryQuery) First(ctx context.Context) (*CloudRepository, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cloudrepository.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CloudRepositoryQuery) FirstX(ctx context.Context) *CloudRepository {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CloudRepository ID from the query.
// Returns a *NotFoundError when no CloudRepository ID was found.
func (_q *CloudRepositoryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cloudrepository.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CloudRepositoryQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CloudRepository entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CloudRepository entity is found.
// Returns a *NotFoundError when no CloudRepository entities are found.
func (_q *CloudRepositoryQuery) Only(ctx context.Context) (*CloudRepository, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cloudrepository.Label}
	default:
		return nil, &NotSingularError{cloudrepository.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CloudRepositoryQuery) OnlyX(ctx context.Context) *CloudRepository {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CloudRepository ID in the query.
// Returns a *NotSingularError when more than one CloudRepository ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CloudRepositoryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cloudrepository.Label}
	default:
		err = &NotSingularError{cloudrepository.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CloudRepositoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CloudRepositories.
func (_q *CloudRepositoryQuery) All(ctx context.Context) ([]*CloudRepository, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CloudRepository, *CloudRepositoryQuery]()
	return withInterceptors[[]*CloudRepository](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CloudRepositoryQuery) AllX(ctx context.Context) []*CloudRepository {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CloudRepository IDs.
func (_q *CloudRepositoryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(cloudrepository.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CloudRepositoryQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CloudRepositoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CloudRepositoryQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CloudRepositoryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CloudRepositoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CloudRepositoryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CloudRepositoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CloudRepositoryQuery) Clone() *CloudRepositoryQuery {
	if _q == nil {
		return nil
	}
	return &CloudRepositoryQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]cloudrepository.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.CloudRepository{}, _q.predicates...),
		withRepository: _q.withRepository.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithRepository tells the query-builder to eager-load the nodes that are connected to
// the "repository" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CloudRepositoryQuery) WithRepository(opts ...func(*RepositoryQuery)) *CloudRepositoryQuery {
	query := (&RepositoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRepository = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CloudRepository.Query().
//		GroupBy(cloudrepository.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CloudRepositoryQuery) GroupBy(field string, fields ...string) *CloudRepositoryGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CloudRepositoryGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = cloudrepository.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt"`
//	}
//
//	client.CloudRepository.Query().
//		Select(cloudrepository.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *CloudRepositoryQuery) Select(fields ...string) *CloudRepositorySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CloudRepositorySelect{CloudRepositoryQuery: _q}
	sbuild.label = cloudrepository.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CloudRepositorySelect configured with the given aggregations.
func (_q *CloudRepositoryQuery) Aggregate(fns ...AggregateFunc) *CloudRepositorySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CloudRepositoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !cloudrepository.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CloudRepositoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CloudRepository, error) {
	var (
		nodes       = []*CloudRepository{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withRepository != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CloudRepository).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CloudRepository{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRepository; query != nil {
		if err := _q.loadRepository(ctx, query, nodes, nil,
			func(n *CloudRepository, e *Repository) { n.Edges.Repository = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CloudRepositoryQuery) loadRepository(ctx context.Context, query *RepositoryQuery, nodes []*CloudRepository, init func(*CloudRepository), assign func(*CloudRepository, *Repository)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*CloudRepository)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.Repository(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(cloudrepository.RepositoryColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.cloud_repository_repository
		if fk == nil {
			return fmt.Errorf(`foreign-key "cloud_repository_repository" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "cloud_repository_repository" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *CloudRepositoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CloudRepositoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cloudrepository.Table, cloudrepository.Columns, sqlgraph.NewFieldSpec(cloudrepository.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cloudrepository.FieldID)
		for i := range fields {
			if fields[i] != cloudrepository.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CloudRepositoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(cloudrepository.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = cloudrepository.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *CloudRepositoryQuery) Modify(modifiers ...func(s *sql.Selector)) *CloudRepositorySelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// CloudRepositoryGroupBy is the group-by builder for CloudRepository entities.
type CloudRepositoryGroupBy struct {
	selector
	build *CloudRepositoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CloudRepositoryGroupBy) Aggregate(fns ...AggregateFunc) *CloudRepositoryGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CloudRepositoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CloudRepositoryQuery, *CloudRepositoryGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CloudRepositoryGroupBy) sqlScan(ctx context.Context, root *CloudRepositoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CloudRepositorySelect is the builder for selecting fields of CloudRepository entities.
type CloudRepositorySelect struct {
	*CloudRepositoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CloudRepositorySelect) Aggregate(fns ...AggregateFunc) *CloudRepositorySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CloudRepositorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CloudRepositoryQuery, *CloudRepositorySelect](ctx, _s.CloudRepositoryQuery, _s, _s.inters, v)
}

func (_s *CloudRepositorySelect) sqlScan(ctx context.Context, root *CloudRepositoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *CloudRepositorySelect) Modify(modifiers ...func(s *sql.Selector)) *CloudRepositorySelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
