// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loomi-labs/arco/backend/ent/archive"
	"github.com/loomi-labs/arco/backend/ent/backupprofile"
	"github.com/loomi-labs/arco/backend/ent/cloudrepository"
	"github.com/loomi-labs/arco/backend/ent/notification"
	"github.com/loomi-labs/arco/backend/ent/repository"
)

// RepositoryCreate is the builder for creating a Repository entity.
type RepositoryCreate struct {
	config
	mutation *RepositoryMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *RepositoryCreate) SetCreatedAt(v time.Time) *RepositoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableCreatedAt(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RepositoryCreate) SetUpdatedAt(v time.Time) *RepositoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableUpdatedAt(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *RepositoryCreate) SetName(v string) *RepositoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *RepositoryCreate) SetURL(v string) *RepositoryCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetHasPassword sets the "has_password" field.
func (_c *RepositoryCreate) SetHasPassword(v bool) *RepositoryCreate {
	_c.mutation.SetHasPassword(v)
	return _c
}

// SetNillableHasPassword sets the "has_password" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableHasPassword(v *bool) *RepositoryCreate {
	if v != nil {
		_c.SetHasPassword(*v)
	}
	return _c
}

// SetLastQuickCheckAt sets the "last_quick_check_at" field.
func (_c *RepositoryCreate) SetLastQuickCheckAt(v time.Time) *RepositoryCreate {
	_c.mutation.SetLastQuickCheckAt(v)
	return _c
}

// SetNillableLastQuickCheckAt sets the "last_quick_check_at" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableLastQuickCheckAt(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetLastQuickCheckAt(*v)
	}
	return _c
}

// SetQuickCheckError sets the "quick_check_error" field.
func (_c *RepositoryCreate) SetQuickCheckError(v []string) *RepositoryCreate {
	_c.mutation.SetQuickCheckError(v)
	return _c
}

// SetLastFullCheckAt sets the "last_full_check_at" field.
func (_c *RepositoryCreate) SetLastFullCheckAt(v time.Time) *RepositoryCreate {
	_c.mutation.SetLastFullCheckAt(v)
	return _c
}

// SetNillableLastFullCheckAt sets the "last_full_check_at" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableLastFullCheckAt(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetLastFullCheckAt(*v)
	}
	return _c
}

// SetFullCheckError sets the "full_check_error" field.
func (_c *RepositoryCreate) SetFullCheckError(v []string) *RepositoryCreate {
	_c.mutation.SetFullCheckError(v)
	return _c
}

// SetStatsTotalChunks sets the "stats_total_chunks" field.
func (_c *RepositoryCreate) SetStatsTotalChunks(v int) *RepositoryCreate {
	_c.mutation.SetStatsTotalChunks(v)
	return _c
}

// SetNillableStatsTotalChunks sets the "stats_total_chunks" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableStatsTotalChunks(v *int) *RepositoryCreate {
	if v != nil {
		_c.SetStatsTotalChunks(*v)
	}
	return _c
}

// SetStatsTotalSize sets the "stats_total_size" field.
func (_c *RepositoryCreate) SetStatsTotalSize(v int) *RepositoryCreate {
	_c.mutation.SetStatsTotalSize(v)
	return _c
}

// SetNillableStatsTotalSize sets the "stats_total_size" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableStatsTotalSize(v *int) *RepositoryCreate {
	if v != nil {
		_c.SetStatsTotalSize(*v)
	}
	return _c
}

// SetStatsTotalCsize sets the "stats_total_csize" field.
func (_c *RepositoryCreate) SetStatsTotalCsize(v int) *RepositoryCreate {
	_c.mutation.SetStatsTotalCsize(v)
	return _c
}

// SetNillableStatsTotalCsize sets the "stats_total_csize" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableStatsTotalCsize(v *int) *RepositoryCreate {
	if v != nil {
		_c.SetStatsTotalCsize(*v)
	}
	return _c
}

// SetStatsTotalUniqueChunks sets the "stats_total_unique_chunks" field.
func (_c *RepositoryCreate) SetStatsTotalUniqueChunks(v int) *RepositoryCreate {
	_c.mutation.SetStatsTotalUniqueChunks(v)
	return _c
}

// SetNillableStatsTotalUniqueChunks sets the "stats_total_unique_chunks" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableStatsTotalUniqueChunks(v *int) *RepositoryCreate {
	if v != nil {
		_c.SetStatsTotalUniqueChunks(*v)
	}
	return _c
}

// SetStatsUniqueSize sets the "stats_unique_size" field.
func (_c *RepositoryCreate) SetStatsUniqueSize(v int) *RepositoryCreate {
	_c.mutation.SetStatsUniqueSize(v)
	return _c
}

// SetNillableStatsUniqueSize sets the "stats_unique_size" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableStatsUniqueSize(v *int) *RepositoryCreate {
	if v != nil {
		_c.SetStatsUniqueSize(*v)
	}
	return _c
}

// SetStatsUniqueCsize sets the "stats_unique_csize" field.
func (_c *RepositoryCreate) SetStatsUniqueCsize(v int) *RepositoryCreate {
	_c.mutation.SetStatsUniqueCsize(v)
	return _c
}

// SetNillableStatsUniqueCsize sets the "stats_unique_csize" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableStatsUniqueCsize(v *int) *RepositoryCreate {
	if v != nil {
		_c.SetStatsUniqueCsize(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RepositoryCreate) SetID(v int) *RepositoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddBackupProfileIDs adds the "backup_profiles" edge to the BackupProfile entity by IDs.
func (_c *RepositoryCreate) AddBackupProfileIDs(ids ...int) *RepositoryCreate {
	_c.mutation.AddBackupProfileIDs(ids...)
	return _c
}

// AddBackupProfiles adds the "backup_profiles" edges to the BackupProfile entity.
func (_c *RepositoryCreate) AddBackupProfiles(v ...*BackupProfile) *RepositoryCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBackupProfileIDs(ids...)
}

// AddArchiveIDs adds the "archives" edge to the Archive entity by IDs.
func (_c *RepositoryCreate) AddArchiveIDs(ids ...int) *RepositoryCreate {
	_c.mutation.AddArchiveIDs(ids...)
	return _c
}

// AddArchives adds the "archives" edges to the Archive entity.
func (_c *RepositoryCreate) AddArchives(v ...*Archive) *RepositoryCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddArchiveIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (_c *RepositoryCreate) AddNotificationIDs(ids ...int) *RepositoryCreate {
	_c.mutation.AddNotificationIDs(ids...)
	return _c
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (_c *RepositoryCreate) AddNotifications(v ...*Notification) *RepositoryCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNotificationIDs(ids...)
}

// SetCloudRepositoryID sets the "cloud_repository" edge to the CloudRepository entity by ID.
func (_c *RepositoryCreate) SetCloudRepositoryID(id int) *RepositoryCreate {
	_c.mutation.SetCloudRepositoryID(id)
	return _c
}

// SetNillableCloudRepositoryID sets the "cloud_repository" edge to the CloudRepository entity by ID if the given value is not nil.
func (_c *RepositoryCreate) SetNillableCloudRepositoryID(id *int) *RepositoryCreate {
	if id != nil {
		_c = _c.SetCloudRepositoryID(*id)
	}
	return _c
}

// SetCloudRepository sets the "cloud_repository" edge to the CloudRepository entity.
func (_c *RepositoryCreate) SetCloudRepository(v *CloudRepository) *RepositoryCreate {
	return _c.SetCloudRepositoryID(v.ID)
}

// Mutation returns the RepositoryMutation object of the builder.
func (_c *RepositoryCreate) Mutation() *RepositoryMutation {
	return _c.mutation
}

// Save creates the Repository in the database.
func (_c *RepositoryCreate) Save(ctx context.Context) (*Repository, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RepositoryCreate) SaveX(ctx context.Context) *Repository {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepositoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepositoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RepositoryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := repository.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := repository.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.HasPassword(); !ok {
		v := repository.DefaultHasPassword
		_c.mutation.SetHasPassword(v)
	}
	if _, ok := _c.mutation.StatsTotalChunks(); !ok {
		v := repository.DefaultStatsTotalChunks
		_c.mutation.SetStatsTotalChunks(v)
	}
	if _, ok := _c.mutation.StatsTotalSize(); !ok {
		v := repository.DefaultStatsTotalSize
		_c.mutation.SetStatsTotalSize(v)
	}
	if _, ok := _c.mutation.StatsTotalCsize(); !ok {
		v := repository.DefaultStatsTotalCsize
		_c.mutation.SetStatsTotalCsize(v)
	}
	if _, ok := _c.mutation.StatsTotalUniqueChunks(); !ok {
		v := repository.DefaultStatsTotalUniqueChunks
		_c.mutation.SetStatsTotalUniqueChunks(v)
	}
	if _, ok := _c.mutation.StatsUniqueSize(); !ok {
		v := repository.DefaultStatsUniqueSize
		_c.mutation.SetStatsUniqueSize(v)
	}
	if _, ok := _c.mutation.StatsUniqueCsize(); !ok {
		v := repository.DefaultStatsUniqueCsize
		_c.mutation.SetStatsUniqueCsize(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RepositoryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Repository.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Repository.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Repository.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := repository.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Repository.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Repository.url"`)}
	}
	if _, ok := _c.mutation.HasPassword(); !ok {
		return &ValidationError{Name: "has_password", err: errors.New(`ent: missing required field "Repository.has_password"`)}
	}
	if _, ok := _c.mutation.StatsTotalChunks(); !ok {
		return &ValidationError{Name: "stats_total_chunks", err: errors.New(`ent: missing required field "Repository.stats_total_chunks"`)}
	}
	if _, ok := _c.mutation.StatsTotalSize(); !ok {
		return &ValidationError{Name: "stats_total_size", err: errors.New(`ent: missing required field "Repository.stats_total_size"`)}
	}
	if _, ok := _c.mutation.StatsTotalCsize(); !ok {
		return &ValidationError{Name: "stats_total_csize", err: errors.New(`ent: missing required field "Repository.stats_total_csize"`)}
	}
	if _, ok := _c.mutation.StatsTotalUniqueChunks(); !ok {
		return &ValidationError{Name: "stats_total_unique_chunks", err: errors.New(`ent: missing required field "Repository.stats_total_unique_chunks"`)}
	}
	if _, ok := _c.mutation.StatsUniqueSize(); !ok {
		return &ValidationError{Name: "stats_unique_size", err: errors.New(`ent: missing required field "Repository.stats_unique_size"`)}
	}
	if _, ok := _c.mutation.StatsUniqueCsize(); !ok {
		return &ValidationError{Name: "stats_unique_csize", err: errors.New(`ent: missing required field "Repository.stats_unique_csize"`)}
	}
	return nil
}

func (_c *RepositoryCreate) sqlSave(ctx context.Context) (*Repository, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RepositoryCreate) createSpec() (*Repository, *sqlgraph.CreateSpec) {
	var (
		_node = &Repository{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(repository.Table, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(repository.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(repository.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(repository.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(repository.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.HasPassword(); ok {
		_spec.SetField(repository.FieldHasPassword, field.TypeBool, value)
		_node.HasPassword = value
	}
	if value, ok := _c.mutation.LastQuickCheckAt(); ok {
		_spec.SetField(repository.FieldLastQuickCheckAt, field.TypeTime, value)
		_node.LastQuickCheckAt = &value
	}
	if value, ok := _c.mutation.QuickCheckError(); ok {
		_spec.SetField(repository.FieldQuickCheckError, field.TypeJSON, value)
		_node.QuickCheckError = value
	}
	if value, ok := _c.mutation.LastFullCheckAt(); ok {
		_spec.SetField(repository.FieldLastFullCheckAt, field.TypeTime, value)
		_node.LastFullCheckAt = &value
	}
	if value, ok := _c.mutation.FullCheckError(); ok {
		_spec.SetField(repository.FieldFullCheckError, field.TypeJSON, value)
		_node.FullCheckError = value
	}
	if value, ok := _c.mutation.StatsTotalChunks(); ok {
		_spec.SetField(repository.FieldStatsTotalChunks, field.TypeInt, value)
		_node.StatsTotalChunks = value
	}
	if value, ok := _c.mutation.StatsTotalSize(); ok {
		_spec.SetField(repository.FieldStatsTotalSize, field.TypeInt, value)
		_node.StatsTotalSize = value
	}
	if value, ok := _c.mutation.StatsTotalCsize(); ok {
		_spec.SetField(repository.FieldStatsTotalCsize, field.TypeInt, value)
		_node.StatsTotalCsize = value
	}
	if value, ok := _c.mutation.StatsTotalUniqueChunks(); ok {
		_spec.SetField(repository.FieldStatsTotalUniqueChunks, field.TypeInt, value)
		_node.StatsTotalUniqueChunks = value
	}
	if value, ok := _c.mutation.StatsUniqueSize(); ok {
		_spec.SetField(repository.FieldStatsUniqueSize, field.TypeInt, value)
		_node.StatsUniqueSize = value
	}
	if value, ok := _c.mutation.StatsUniqueCsize(); ok {
		_spec.SetField(repository.FieldStatsUniqueCsize, field.TypeInt, value)
		_node.StatsUniqueCsize = value
	}
	if nodes := _c.mutation.BackupProfilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   repository.BackupProfilesTable,
			Columns: repository.BackupProfilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backupprofile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ArchivesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   repository.ArchivesTable,
			Columns: []string{repository.ArchivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(archive.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   repository.NotificationsTable,
			Columns: []string{repository.NotificationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CloudRepositoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   repository.CloudRepositoryTable,
			Columns: []string{repository.CloudRepositoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cloudrepository.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.cloud_repository_repository = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RepositoryCreateBulk is the builder for creating many Repository entities in bulk.
type RepositoryCreateBulk struct {
	config
	err      error
	builders []*RepositoryCreate
}

// Save creates the Repository entities in the database.
func (_c *RepositoryCreateBulk) Save(ctx context.Context) ([]*Repository, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Repository, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RepositoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RepositoryCreateBulk) SaveX(ctx context.Context) []*Repository {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepositoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepositoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
