// Code generated by ent, DO NOT EDIT.

package backupprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/loomi-labs/arco/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldName, v))
}

// Prefix applies equality check predicate on the "prefix" field. It's identical to PrefixEQ.
func Prefix(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldPrefix, v))
}

// ExcludeCaches applies equality check predicate on the "exclude_caches" field. It's identical to ExcludeCachesEQ.
func ExcludeCaches(v bool) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldExcludeCaches, v))
}

// CompressionLevel applies equality check predicate on the "compression_level" field. It's identical to CompressionLevelEQ.
func CompressionLevel(v int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldCompressionLevel, v))
}

// DataSectionCollapsed applies equality check predicate on the "data_section_collapsed" field. It's identical to DataSectionCollapsedEQ.
func DataSectionCollapsed(v bool) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldDataSectionCollapsed, v))
}

// ScheduleSectionCollapsed applies equality check predicate on the "schedule_section_collapsed" field. It's identical to ScheduleSectionCollapsedEQ.
func ScheduleSectionCollapsed(v bool) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldScheduleSectionCollapsed, v))
}

// AdvancedSectionCollapsed applies equality check predicate on the "advanced_section_collapsed" field. It's identical to AdvancedSectionCollapsedEQ.
func AdvancedSectionCollapsed(v bool) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldAdvancedSectionCollapsed, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldContainsFold(FieldName, v))
}

// PrefixEQ applies the EQ predicate on the "prefix" field.
func PrefixEQ(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldPrefix, v))
}

// PrefixNEQ applies the NEQ predicate on the "prefix" field.
func PrefixNEQ(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNEQ(FieldPrefix, v))
}

// PrefixIn applies the In predicate on the "prefix" field.
func PrefixIn(vs ...string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldIn(FieldPrefix, vs...))
}

// PrefixNotIn applies the NotIn predicate on the "prefix" field.
func PrefixNotIn(vs ...string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNotIn(FieldPrefix, vs...))
}

// PrefixGT applies the GT predicate on the "prefix" field.
func PrefixGT(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldGT(FieldPrefix, v))
}

// PrefixGTE applies the GTE predicate on the "prefix" field.
func PrefixGTE(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldGTE(FieldPrefix, v))
}

// PrefixLT applies the LT predicate on the "prefix" field.
func PrefixLT(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldLT(FieldPrefix, v))
}

// PrefixLTE applies the LTE predicate on the "prefix" field.
func PrefixLTE(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldLTE(FieldPrefix, v))
}

// PrefixContains applies the Contains predicate on the "prefix" field.
func PrefixContains(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldContains(FieldPrefix, v))
}

// PrefixHasPrefix applies the HasPrefix predicate on the "prefix" field.
func PrefixHasPrefix(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldHasPrefix(FieldPrefix, v))
}

// PrefixHasSuffix applies the HasSuffix predicate on the "prefix" field.
func PrefixHasSuffix(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldHasSuffix(FieldPrefix, v))
}

// PrefixEqualFold applies the EqualFold predicate on the "prefix" field.
func PrefixEqualFold(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEqualFold(FieldPrefix, v))
}

// PrefixContainsFold applies the ContainsFold predicate on the "prefix" field.
func PrefixContainsFold(v string) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldContainsFold(FieldPrefix, v))
}

// ExcludePathsIsNil applies the IsNil predicate on the "exclude_paths" field.
func ExcludePathsIsNil() predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldIsNull(FieldExcludePaths))
}

// ExcludePathsNotNil applies the NotNil predicate on the "exclude_paths" field.
func ExcludePathsNotNil() predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNotNull(FieldExcludePaths))
}

// ExcludeCachesEQ applies the EQ predicate on the "exclude_caches" field.
func ExcludeCachesEQ(v bool) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldExcludeCaches, v))
}

// ExcludeCachesNEQ applies the NEQ predicate on the "exclude_caches" field.
func ExcludeCachesNEQ(v bool) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNEQ(FieldExcludeCaches, v))
}

// IconEQ applies the EQ predicate on the "icon" field.
func IconEQ(v Icon) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldIcon, v))
}

// IconNEQ applies the NEQ predicate on the "icon" field.
func IconNEQ(v Icon) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNEQ(FieldIcon, v))
}

// IconIn applies the In predicate on the "icon" field.
func IconIn(vs ...Icon) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldIn(FieldIcon, vs...))
}

// IconNotIn applies the NotIn predicate on the "icon" field.
func IconNotIn(vs ...Icon) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNotIn(FieldIcon, vs...))
}

// CompressionModeEQ applies the EQ predicate on the "compression_mode" field.
func CompressionModeEQ(v CompressionMode) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldCompressionMode, v))
}

// CompressionModeNEQ applies the NEQ predicate on the "compression_mode" field.
func CompressionModeNEQ(v CompressionMode) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNEQ(FieldCompressionMode, v))
}

// CompressionModeIn applies the In predicate on the "compression_mode" field.
func CompressionModeIn(vs ...CompressionMode) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldIn(FieldCompressionMode, vs...))
}

// CompressionModeNotIn applies the NotIn predicate on the "compression_mode" field.
func CompressionModeNotIn(vs ...CompressionMode) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNotIn(FieldCompressionMode, vs...))
}

// CompressionLevelEQ applies the EQ predicate on the "compression_level" field.
func CompressionLevelEQ(v int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldCompressionLevel, v))
}

// CompressionLevelNEQ applies the NEQ predicate on the "compression_level" field.
func CompressionLevelNEQ(v int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNEQ(FieldCompressionLevel, v))
}

// CompressionLevelIn applies the In predicate on the "compression_level" field.
func CompressionLevelIn(vs ...int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldIn(FieldCompressionLevel, vs...))
}

// CompressionLevelNotIn applies the NotIn predicate on the "compression_level" field.
func CompressionLevelNotIn(vs ...int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNotIn(FieldCompressionLevel, vs...))
}

// CompressionLevelGT applies the GT predicate on the "compression_level" field.
func CompressionLevelGT(v int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldGT(FieldCompressionLevel, v))
}

// CompressionLevelGTE applies the GTE predicate on the "compression_level" field.
func CompressionLevelGTE(v int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldGTE(FieldCompressionLevel, v))
}

// CompressionLevelLT applies the LT predicate on the "compression_level" field.
func CompressionLevelLT(v int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldLT(FieldCompressionLevel, v))
}

// CompressionLevelLTE applies the LTE predicate on the "compression_level" field.
func CompressionLevelLTE(v int) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldLTE(FieldCompressionLevel, v))
}

// CompressionLevelIsNil applies the IsNil predicate on the "compression_level" field.
func CompressionLevelIsNil() predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldIsNull(FieldCompressionLevel))
}

// CompressionLevelNotNil applies the NotNil predicate on the "compression_level" field.
func CompressionLevelNotNil() predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNotNull(FieldCompressionLevel))
}

// DataSectionCollapsedEQ applies the EQ predicate on the "data_section_collapsed" field.
func DataSectionCollapsedEQ(v bool) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldDataSectionCollapsed, v))
}

// DataSectionCollapsedNEQ applies the NEQ predicate on the "data_section_collapsed" field.
func DataSectionCollapsedNEQ(v bool) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNEQ(FieldDataSectionCollapsed, v))
}

// ScheduleSectionCollapsedEQ applies the EQ predicate on the "schedule_section_collapsed" field.
func ScheduleSectionCollapsedEQ(v bool) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldScheduleSectionCollapsed, v))
}

// ScheduleSectionCollapsedNEQ applies the NEQ predicate on the "schedule_section_collapsed" field.
func ScheduleSectionCollapsedNEQ(v bool) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNEQ(FieldScheduleSectionCollapsed, v))
}

// AdvancedSectionCollapsedEQ applies the EQ predicate on the "advanced_section_collapsed" field.
func AdvancedSectionCollapsedEQ(v bool) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldEQ(FieldAdvancedSectionCollapsed, v))
}

// AdvancedSectionCollapsedNEQ applies the NEQ predicate on the "advanced_section_collapsed" field.
func AdvancedSectionCollapsedNEQ(v bool) predicate.BackupProfile {
	return predicate.BackupProfile(sql.FieldNEQ(FieldAdvancedSectionCollapsed, v))
}

// HasRepositories applies the HasEdge predicate on the "repositories" edge.
func HasRepositories() predicate.BackupProfile {
	return predicate.BackupProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, RepositoriesTable, RepositoriesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRepositoriesWith applies the HasEdge predicate on the "repositories" edge with a given conditions (other predicates).
func HasRepositoriesWith(preds ...predicate.Repository) predicate.BackupProfile {
	return predicate.BackupProfile(func(s *sql.Selector) {
		step := newRepositoriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasArchives applies the HasEdge predicate on the "archives" edge.
func HasArchives() predicate.BackupProfile {
	return predicate.BackupProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ArchivesTable, ArchivesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArchivesWith applies the HasEdge predicate on the "archives" edge with a given conditions (other predicates).
func HasArchivesWith(preds ...predicate.Archive) predicate.BackupProfile {
	return predicate.BackupProfile(func(s *sql.Selector) {
		step := newArchivesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBackupSchedule applies the HasEdge predicate on the "backup_schedule" edge.
func HasBackupSchedule() predicate.BackupProfile {
	return predicate.BackupProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, BackupScheduleTable, BackupScheduleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBackupScheduleWith applies the HasEdge predicate on the "backup_schedule" edge with a given conditions (other predicates).
func HasBackupScheduleWith(preds ...predicate.BackupSchedule) predicate.BackupProfile {
	return predicate.BackupProfile(func(s *sql.Selector) {
		step := newBackupScheduleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPruningRule applies the HasEdge predicate on the "pruning_rule" edge.
func HasPruningRule() predicate.BackupProfile {
	return predicate.BackupProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, PruningRuleTable, PruningRuleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPruningRuleWith applies the HasEdge predicate on the "pruning_rule" edge with a given conditions (other predicates).
func HasPruningRuleWith(preds ...predicate.PruningRule) predicate.BackupProfile {
	return predicate.BackupProfile(func(s *sql.Selector) {
		step := newPruningRuleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNotifications applies the HasEdge predicate on the "notifications" edge.
func HasNotifications() predicate.BackupProfile {
	return predicate.BackupProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, NotificationsTable, NotificationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNotificationsWith applies the HasEdge predicate on the "notifications" edge with a given conditions (other predicates).
func HasNotificationsWith(preds ...predicate.Notification) predicate.BackupProfile {
	return predicate.BackupProfile(func(s *sql.Selector) {
		step := newNotificationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BackupProfile) predicate.BackupProfile {
	return predicate.BackupProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BackupProfile) predicate.BackupProfile {
	return predicate.BackupProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BackupProfile) predicate.BackupProfile {
	return predicate.BackupProfile(sql.NotPredicates(p))
}
