// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service contains the business logic for notifications
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ent$0 from "../../ent/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DismissAllErrors marks all unseen error notifications as seen
 */
export function DismissAllErrors(): $CancellablePromise<void> {
    return $Call.ByID(666801431);
}

/**
 * DismissError marks a notification as seen (dismissed)
 */
export function DismissError(id: number): $CancellablePromise<void> {
    return $Call.ByID(3134415493, id);
}

/**
 * GetUnseenErrorCounts returns counts of unseen errors per repository and backup profile
 */
export function GetUnseenErrorCounts(): $CancellablePromise<$models.ErrorCounts | null> {
    return $Call.ByID(692371165).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetUnseenErrors returns all unseen error notifications with their related entities
 */
export function GetUnseenErrors(): $CancellablePromise<$models.ErrorNotification[]> {
    return $Call.ByID(2966536490).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Init initializes the service with database client and event emitter
 */
export function Init(db: ent$0.Client | null, eventEmitter: types$0.EventEmitter): $CancellablePromise<void> {
    return $Call.ByID(28573893, db, eventEmitter);
}

// Private type creation functions
const $$createType0 = $models.ErrorCounts.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ErrorNotification.createFrom;
const $$createType3 = $Create.Array($$createType2);
