// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ent} from '../models';
import {app} from '../models';

export function AddBackupProfile(arg1:number,arg2:number):Promise<ent.Repository>;

export function AddExistingRepository(arg1:string,arg2:string,arg3:string,arg4:number):Promise<ent.Repository>;

export function All():Promise<Array<ent.Repository>>;

export function Create(arg1:string,arg2:string,arg3:string,arg4:number):Promise<ent.Repository>;

export function DeleteArchive(arg1:number):Promise<void>;

export function Get(arg1:number):Promise<ent.Repository>;

export function GetArchiveMountStates(arg1:number):Promise<{[key: number]: app.MountState}>;

export function GetRepositoryMountState(arg1:number):Promise<app.MountState>;

export function MountArchive(arg1:number):Promise<app.MountState>;

export function MountRepository(arg1:number):Promise<app.MountState>;

export function RefreshArchives(arg1:number):Promise<Array<ent.Archive>>;

export function UnmountArchive(arg1:number):Promise<app.MountState>;

export function UnmountRepository(arg1:number):Promise<app.MountState>;
