// Code generated by MockGen. DO NOT EDIT.
// Source: backend/app/types/types.go
//
// Generated by this command:
//
//	mockgen -source=backend/app/types/types.go -destination=backend/app/mockapp/mocktypes/mocktypes.go --package=mocktypes
//

// Package mocktypes is a generated GoMock package.
package mocktypes
