// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backup() {
  return window['go']['borg']['Borg']['Backup']();
}

export function ConnectExistingRepo() {
  return window['go']['borg']['Borg']['ConnectExistingRepo']();
}

export function CreateSSHKeyPair() {
  return window['go']['borg']['Borg']['CreateSSHKeyPair']();
}

export function GetBackupSet(arg1) {
  return window['go']['borg']['Borg']['GetBackupSet'](arg1);
}

export function GetBackupSets() {
  return window['go']['borg']['Borg']['GetBackupSets']();
}

export function InitRepo(arg1) {
  return window['go']['borg']['Borg']['InitRepo'](arg1);
}

export function List() {
  return window['go']['borg']['Borg']['List']();
}

export function NewBackupSet() {
  return window['go']['borg']['Borg']['NewBackupSet']();
}

export function Prune() {
  return window['go']['borg']['Borg']['Prune']();
}

export function Version() {
  return window['go']['borg']['Borg']['Version']();
}
