// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackupClient is a client for backup related operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as state$0 from "./state/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$1 from "../borg/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ent$0 from "../ent/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AbortBackupJobs(bIds: types$0.BackupId[]): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(158665837, bIds) as any;
    return $resultPromise;
}

export function AddRepositoryToBackupProfile(backupProfileId: number, repositoryId: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2277303818, backupProfileId, repositoryId) as any;
    return $resultPromise;
}

export function CreateBackupProfile(backup: ent$0.BackupProfile, repositoryIds: number[]): Promise<ent$0.BackupProfile | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1869117442, backup, repositoryIds) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function CreateDirectory(path: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(384386562, path) as any;
    return $resultPromise;
}

export function DeleteBackupProfile(backupProfileId: number, deleteArchives: boolean): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2748646819, backupProfileId, deleteArchives) as any;
    return $resultPromise;
}

export function DoesPathExist(path: string): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2517090612, path) as any;
    return $resultPromise;
}

export function ExaminePrunes(backupProfileId: number, pruningRule: ent$0.PruningRule | null, saveResults: boolean): Promise<$models.ExaminePruningResult[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3315475643, backupProfileId, pruningRule, saveResults) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetBackupButtonStatus(bIds: types$0.BackupId[]): Promise<state$0.BackupButtonStatus> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1193421857, bIds) as any;
    return $resultPromise;
}

export function GetBackupProfile(id: number): Promise<ent$0.BackupProfile | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4228689432, id) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetBackupProfileFilterOptions(repoId: number): Promise<$models.BackupProfileFilter[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(169520516, repoId) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetBackupProfiles(): Promise<(ent$0.BackupProfile | null)[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(855020145) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType6($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetCombinedBackupProgress(bIds: types$0.BackupId[]): Promise<types$1.BackupProgress | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2559126927, bIds) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType8($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetDirectorySuggestions(): Promise<string[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2682457829) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType9($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetLastBackupErrorMsg(bId: types$0.BackupId): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3222434012, bId) as any;
    return $resultPromise;
}

export function GetPrefixSuggestion(name: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2653689665, name) as any;
    return $resultPromise;
}

export function GetPruningOptions(): Promise<$models.GetPruningOptionsResponse> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2377421126) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType10($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function GetState(bId: types$0.BackupId): Promise<state$0.BackupState> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1185260030, bId) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType11($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function IsDirectory(path: string): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2744183134, path) as any;
    return $resultPromise;
}

export function IsDirectoryEmpty(path: string): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2479767251, path) as any;
    return $resultPromise;
}

export function NewBackupProfile(): Promise<ent$0.BackupProfile | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3671076802) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function RemoveRepositoryFromBackupProfile(backupProfileId: number, repositoryId: number, deleteArchives: boolean): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2324600110, backupProfileId, repositoryId, deleteArchives) as any;
    return $resultPromise;
}

export function SaveBackupSchedule(backupProfileId: number, schedule: ent$0.BackupSchedule): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1024354325, backupProfileId, schedule) as any;
    return $resultPromise;
}

export function SavePruningRule(backupId: number, rule: ent$0.PruningRule): Promise<ent$0.PruningRule | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(519732571, backupId, rule) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType13($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function SelectDirectory(data: $models.SelectDirectoryData): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1473199266, data) as any;
    return $resultPromise;
}

export function StartBackupJobs(bIds: types$0.BackupId[]): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1345090683, bIds) as any;
    return $resultPromise;
}

export function StartPruneJob(bId: types$0.BackupId): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2502566490, bId) as any;
    return $resultPromise;
}

export function UpdateBackupProfile(backup: ent$0.BackupProfile): Promise<ent$0.BackupProfile | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1168330145, backup) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = ent$0.BackupProfile.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ExaminePruningResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.BackupProfileFilter.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($$createType1);
const $$createType7 = types$1.BackupProgress.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = $models.GetPruningOptionsResponse.createFrom;
const $$createType11 = state$0.BackupState.createFrom;
const $$createType12 = ent$0.PruningRule.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
