// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as state$0 from "../state/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ent$0 from "../../ent/models.js";

export function GetAuthState(): Promise<state$0.AuthState> & { cancel(): void } {
    let $resultPromise = $Call.ByID(216707387) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function Logout(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2333485090) as any;
    return $resultPromise;
}

export function SetDb(db: ent$0.Client | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2557859926, db) as any;
    return $resultPromise;
}

export function StartLogin(email: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4267423869, email) as any;
    return $resultPromise;
}

export function StartRegister(email: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3870237273, email) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = state$0.AuthState.createFrom;
