name: Continuous Integration

on:
  pull_request:
  push:
    branches-ignore: [ "main" ]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  integration-tests:
    uses: ./.github/workflows/integration_tests.yml

  build-check:
    uses: ./.github/workflows/build.yml
    with:
      push_artifacts: false
