name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - 'release-please-**'

jobs:
  release:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/release.yml