name: Create Release PR

on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    if: ! (github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release-please-'))
    uses: ./.github/workflows/create_release_pr.yml