name: Lint and Test

on: push

jobs:
#  lint:
#    uses: ./.github/workflows/lint.yml
#
#  test:
#    uses: ./.github/workflows/test.yml

  build:
#    if: github.ref == 'refs/heads/main'
#    needs:
#      - test
#      - lint
    uses: ./.github/workflows/build.yml

  release:
#    if: github.ref == 'refs/heads/main'
    needs:
      - build
    uses: ./.github/workflows/release.yml