name: Lint and Test

on: push

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  build:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yml