name: Lint and Test

on:
  pull_request:
    types:
      - closed

jobs:
#  lint:
#    uses: ./.github/workflows/lint.yml
#
#  test:
#    uses: ./.github/workflows/test.yml

#  build:
#    if: github.ref == 'refs/heads/main'
#    needs:
#      - test
#      - lint
#    uses: ./.github/workflows/build.yml

#  release:
##    if: github.ref == 'refs/heads/main'
#    needs:
#      - build
#    uses: ./.github/workflows/release.yml
  only-if-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Only if merged
        run: echo "This job will only run if the PR is merged"