name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    #  We only want to create a release when the PR is merged and the branch name starts with 'release-please-'
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release-please-')
    uses: ./.github/workflows/release.yml