name: Create Release PR

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event: ${{ toJson(github.event)
          echo "github.event.head_commit.message: ${{ github.event.head_commit.message }}"

  create-release-pr:
    # We do not want to create a release PR when the push comes from a release
    if: "!startsWith(github.event.head_commit.message, 'chore(main): release')"
    uses: ./.github/workflows/create_release_pr.yml
