name: Lint and Test

on: push

jobs:
#  TODO: Uncomment the following lines to enable linting
#  lint:
#    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  build:
    if: github.ref == 'refs/heads/main'
    needs:
      - test
#      - lint
    uses: ./.github/workflows/build.yml