name: Build

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Create release PR
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: go
      # Upload release artifact
      - name: Upload release artifact
        if: ${{ steps.release.outputs.release_created }}
        run: gh release upload "Wails Build Linux arco" ./artifact/some-build-artifact.zip
#        run: gh release upload ${{ steps.release.outputs.tag_name }} ./artifact/some-build-artifact.zip
