name: Build

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Create release PR
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: go
      - name: Debug show all files
        run: ls -la
      # Upload release artifact
      - name: Upload release artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: gh release upload "Wails Build Linux arco" ./artifact/some-build-artifact.zip
        run: gh release upload ${{ steps.release.outputs.tag_name }} /Users/runner/work/arco/arco/build/bin/arco.app.zip
