name: Build

on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/wails_build.yml

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4
      # Create release PR
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: go
          skip-github-pull-request: true
      # Download release artifact
      - uses: actions/download-artifact@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          path: build-assets
          pattern: arco-*
      # Upload release artifact
      - name: Upload release artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} build-assets/arco-linux/arco-linux.zip build-assets/arco-macos/arco-macos.zip
